baseURL = 'https://www.liqianmo.ink/'
languageCode = 'zh-cn'
title = 'èŠŠå¢¨çš„ä¸ªäººåšå®¢'

theme = 'stack'

# ä¸ªäººèµ„æ–™è®¾ç½®
[params.sidebar]
emoji = "ğŸŒŸ"
subtitle = "å¸Œæœ›æˆ‘çš„åšå®¢å¯¹ä½ æœ‰ç”¨"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.footer]
since = 2025
customText = "Â© æèŠŠå¢¨"

# æ–‡ç« è®¾ç½®
[params.article]
math = true
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"